name: fitness_tracker
description: 适用于Windows平台,是一个专为Windows平台设计的现代化个人健身数据管理系统。它提供了一个用户友好的界面，帮助用户轻松记录和分析他们的健身数据，包括运动类型、持续时间、消耗的卡路里等。该应用程序还支持数据可视化功能，让用户能够直观地了解他们的健身进展和趋势。此外，Fitness-Tracker_Win v1.0 还集成了通知功能，提醒用户保持锻炼习惯，并提供个性化的健身建议。无论是初学者还是经验丰富的健身爱好者，这款应用程序都能满足他们的需求，帮助他们实现健康目标。
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # 基础依赖
  cupertino_icons: ^1.0.5
  provider: ^6.1.1
  intl: ^0.20.2
  shared_preferences: ^2.2.2
  path_provider: ^2.1.0
  
  # HTTP请求
  http: ^1.1.0
  
  # 通知
  fluttertoast: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true